title: "[Core Protocol] <Title>"
labels: ["core-protocol", "discussion-metrics"]
body:
  - type: markdown
    attributes:
      value: |
        # Core Protocol

        **Use Case:** Use this template for inquiries related to the core protocol such as technical behaviour, specifications, or protocol-level interactions.

        ### Before proceeding, please check the [documentation](https://docs.optimism.io/) and the [specs](https://specs.optimism.io/).

  - type: markdown
    attributes:
      value: |
        #### Was there anything unclear or missing?
        Please describe the information you were looking for and where you searched.

  - type: textarea
    id: unclear-info
    attributes:
      label: "Provide details"

  - type: checkboxes
    id: verify-check-discussions
    attributes:
      label: "Did you check for duplicate questions?"
      description: "Please check the existing [discussion](https://github.com/ethereum-optimism/developers/discussions) questions first. [How to search GitHub discussions](https://docs.github.com/en/search-github/searching-on-github/searching-discussions)."
      options:
        - label: "Yes"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        #### Similar Questions or Issues Found
        If yes, please provide links to similar questions or issues you found.

  - type: textarea
    id: duplicate-questions
    attributes:
      label: "Provide details"

  - type: markdown
    attributes:
      value: |
        ## What Kind of Request Is This?

  - type: checkboxes
    id: request-type
    attributes:
      label: "Please select the type of request"
      options:
        - label: "Bug Report"
        - label: "Feature Request"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Description

        ### For Bug Reports:

  - type: markdown
    attributes:
      value: |
        #### Steps to Reproduce
        Please provide a detailed sequence of steps to reproduce the issue. Be as specific as possible to help us understand the scenario.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Provide steps"

  - type: markdown
    attributes:
      value: |
        #### Expected vs. Actual Behaviour
        Describe what you expected to happen vs. what actually happened.

  - type: textarea
    id: expected-actual-behavior
    attributes:
      label: "Provide details"

  - type: markdown
    attributes:
      value: |
        #### Environment Details
        Provide the following information about your setup:

  - type: textarea
    id: software-versions
    attributes:
      label: "Software Versions"
      description: "List the software versions (op-contracts, op-node, op-geth, op-challenger, etc.)."

  - type: textarea
    id: operating-system
    attributes:
      label: "Operating System"
      description: "(Optional) Specify the operating system used."

  - type: textarea
    id: hardware-resources
    attributes:
      label: "Hardware Resources"
      description: "(Optional) Describe the hardware resources, infrastructure setup, or any other relevant settings."

  - type: markdown
    attributes:
      value: |
        #### Configuration Files, Startup Flags & Environment Variables
        Please provide the configuration files, commands, and environment variables used.

  - type: textarea
    id: configuration-files
    attributes:
      label: "Provide configuration details"

  - type: markdown
    attributes:
      value: |
        #### Error Messages / Logs
        Provide any error messages or logs related to the issue. This will help us diagnose the problem faster.

  - type: textarea
    id: error-messages-logs
    attributes:
      label: "Provide error logs"

  - type: markdown
    attributes:
      value: |
        ### For Feature Requests:

  - type: markdown
    attributes:
      value: |
        #### Feature Description
        Provide a clear description of the feature you would like to see implemented.

  - type: textarea
    id: feature-description
    attributes:
      label: "Describe the feature"

  - type: markdown
    attributes:
      value: |
        #### Purpose and Benefits
        Explain the purpose of this feature and how it would benefit users or improve the protocol.

  - type: textarea
    id: purpose-benefits
    attributes:
      label: "Provide purpose and benefits"

  - type: markdown
    attributes:
      value: |
        #### Relevant Context or Examples
        Include any relevant context, use cases, or examples that support your request.

  - type: textarea
    id: context-examples
    attributes:
      label: "Provide context or examples"

  - type: markdown
    attributes:
      value: |
        ## Additional Information

        #### Please provide any additional information that may help us answer your question.
        This could include previous troubleshooting steps you've taken, other resources you have consulted, etc.

  - type: textarea
    id: additional-information
    attributes:
      label: "Additional information"
