title: "[Core Protocol] <Title>"
labels: ["core-protocol", "discussion-metrics"]
body:
  - type: markdown
    attributes:
      value: |
        ### **Before proceeding, please consult the following resources:**

        **Did you check the [documentation](https://docs.optimism.io/) and the [specs](https://specs.optimism.io/)?**
  - type: checkboxes
    id: verify-check-docs
    attributes:
      label: Did you check the documentation and specs?
      options:
        - label: "Yes"
    validations:
      required: true

  - type: textarea
    id: unclear-info
    attributes:
      label: Was there anything unclear or missing?
      description: Please describe the information you were looking for and where you searched.

  - type: markdown
    attributes:
      value: |
        **Did you check for duplicate questions?**

        *Please check the [existing discussions](https://github.com/ethereum-optimism/developers/discussions) or issues first. [How to search GitHub discussions](https://docs.github.com/en/search-github/searching-on-github/searching-discussions).*
  - type: checkboxes
    id: verify-check-discussions
    attributes:
      label: Did you check for duplicate questions?
      options:
        - label: "Yes"
    validations:
      required: true

  - type: textarea
    id: duplicate-questions
    attributes:
      label: Similar questions or issues found
      description: If yes, please provide links to similar questions or issues you found.

  - type: markdown
    attributes:
      value: |
        ### What Kind of Request Is This?

        **Please select the type of request:**
  - type: checkboxes
    id: request-type
    attributes:
      label: Please select the type of request
      options:
        - label: "**Bug Report**\n\n    *Please provide a detailed description of the bug, including steps to reproduce, expected vs. actual behavior, and relevant logs or error messages in the Issue Description section below.*"
        - label: "**Feature Request**\n\n    *Please describe the feature you would like to see, its purpose, and how it would benefit users. Include any relevant context or examples in the Issue Description section below.*"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Description

        ### **For Bug Reports:**

        **Steps to reproduce**

        *Please provide a detailed sequence of steps to reproduce the issue.* 

        *Be as specific as possible to help us understand the scenario:*

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce

  - type: markdown
    attributes:
      value: |
        **Expected vs. actual behaviour:**

  - type: textarea
    id: expected-actual-behavior
    attributes:
      label: Expected vs. Actual Behaviour

  - type: markdown
    attributes:
      value: |
        **Environment Details**

        *Provide the following information about your setup:*

  - type: textarea
    id: software-versions
    attributes:
      label: Software Versions
      description: Software Versions (op-contracts, op-node, op-geth, op-challenger, etc.)

  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      description: Optional

  - type: textarea
    id: hardware-resources
    attributes:
      label: Hardware Resources
      description: Optional, infrastructure setup and ANY other relevant settings.

  - type: markdown
    attributes:
      value: |
        **Configuration files,** **Startup Flags & Environment Variables**

  - type: textarea
    id: configuration-files
    attributes:
      label: Configuration files, Startup Flags & Environment Variables
      description: Please provide the config files, commands you used to start each OP Stack component and any environment variables you set.

  - type: markdown
    attributes:
      value: |
        **Error Messages / Logs**

  - type: textarea
    id: error-messages-logs
    attributes:
      label: Error Messages / Logs
      description: Please paste any error messages or logs related to the issue. Providing logs will help us diagnose the problem faster.

  - type: markdown
    attributes:
      value: |
        ### **For Feature Requests:**

        **Feature Description**

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear description of the feature you would like to see implemented.

  - type: markdown
    attributes:
      value: |
        **Purpose and Benefits**

  - type: textarea
    id: purpose-benefits
    attributes:
      label: Purpose and Benefits
      description: Explain the purpose of this feature and how it would benefit users or improve the protocol.

  - type: markdown
    attributes:
      value: |
        **Relevant Context or Examples**

  - type: textarea
    id: context-examples
    attributes:
      label: Relevant Context or Examples
      description: Include any relevant context, use cases, or examples that support your request.

  - type: markdown
    attributes:
      value: |
        ### Additional Information

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please provide any additional information that may help us answer your question. This could include previous troubleshooting steps you've taken, other resources you have consulted, etc.

  - type: markdown
    attributes:
      value: |
        ### General Feedback

        **How can we improve?**

        *If you have suggestions for improvement or other feedback, **please let us know [HERE](https://github.com/ethereum-optimism/developers/discussions/categories/feedback).***
  - type: textarea
    id: feedback
    attributes:
      label: General Feedback
      description: Please provide your feedback here.
