title: "[Application Development] <Title>"
labels: ["app-development", "discussion-metrics"]
body:
  - type: markdown
    attributes:
      value: |
        # Developing on an OP Chain / OP Stack Chain
        
        Before proceeding, please consult the following resources.

  - type: checkboxes
    id: verify-check-docs
    attributes:
      label: Did you check the documentation?
      description: Please let us know how we can improve our [docs](https://docs.optimism.io/builders/dapp-developers/overview) in the additional information section.
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: verify-check-discussions
    attributes:
      label: Did you check for duplicate questions?
      description: Please check the existing [discussion](https://github.com/ethereum-optimism/developers/discussions) questions first. [How to search GitHub discussions](https://docs.github.com/en/search-github/searching-on-github/searching-discussions)
      options:
        - label: "Yes"
          required: true
         
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please describe, in detail, the issue you are having.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please provide any additional information that may help us answer your question.
