title: "[Miscellaneous] <Title>"
labels: ["miscellaneous", "discussion-metrics"]
body:
  - type: markdown
    attributes:
      value: |
        # Miscellaneous
        
        **Use Case:** Use this template for inquiries that **DO NOT** fit into the core protocol, node operations, deploying the OP stack, or application development categories.
        


  - type: checkboxes
    id: verify-check-docs
    attributes:
      label: "Did you check the documentation and specs?"
      description: "If our [documentation](https://docs.optimism.io/) or [specs](https://specs.optimism.io/) didn't answer your question, please let us know how we can improve them by giving us [feedback](https://github.com/ethereum-optimism/developers/discussions/categories/feedback)."
      options:
        - label: "Yes"
    validations:
      required: true

  - type: textarea
    id: unclear-info
    attributes:
      label: "Was there anything unclear or missing?"
      description: "Please describe the information you were looking for and where you searched."

  - type: checkboxes
    id: verify-check-discussions
    attributes:
      label: "Did you check for duplicate questions?"
      description: "Please check the existing [discussion](https://github.com/ethereum-optimism/developers/discussions) questions first. [How to search GitHub discussions](https://docs.github.com/en/search-github/searching-on-github/searching-discussions)."
      options:
        - label: "Yes"
    validations:
      required: true

  - type: textarea
    id: duplicate-questions
    attributes:
      label: "Similar Questions or Issues Found"
      description: "If yes, please provide links to similar questions or issues you found."

  - type: markdown
    attributes:
      value: |
        ## What Kind of Request Is This?

  - type: checkboxes
    id: request-type
    attributes:
      label: "Please select the type of request"
      options:
        - label: "Bug Report"
        - label: "Feature Request"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Description

        ### For Bug Reports:

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide a detailed sequence of steps to reproduce the issue. Be as specific as possible to help us understand the scenario."

  - type: textarea
    id: expected-actual-behavior
    attributes:
      label: "Expected vs. Actual Behaviour"
      description: "Describe what you expected to happen vs. what actually happened."

  - type: markdown
    attributes:
      value: |
        #### Environment Details

  - type: textarea
    id: software-versions
    attributes:
      label: "Software Versions"
      description: "List the software versions (op-contracts, op-node, op-geth, op-challenger, etc.)."

  - type: textarea
    id: operating-system
    attributes:
      label: "Operating System"
      description: "Specify the operating system used."

  - type: textarea
    id: hardware-resources
    attributes:
      label: "Hardware Resources"
      description: "Describe the hardware resources, infrastructure setup, or any other relevant settings."

  - type: textarea
    id: configuration-files
    attributes:
      label: "Configuration Files, Startup Flags & Environment Variables"
      description: "Please provide the configuration files, commands, and environment variables used."

  - type: textarea
    id: error-messages-logs
    attributes:
      label: "Error Messages / Logs"
      description: "Provide any error messages or logs related to the issue. This will help us diagnose the problem faster."

  - type: markdown
    attributes:
      value: |
        ### For Feature Requests:

  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Provide a clear description of the feature you would like to see implemented."

  - type: textarea
    id: purpose-benefits
    attributes:
      label: "Purpose and Benefits"
      description: "Explain the purpose of this feature and how it would benefit users or improve the protocol."

  - type: textarea
    id: context-examples
    attributes:
      label: "Relevant Context or Examples"
      description: "Include any relevant context, use cases, or examples that support your request."
