title: "[Node Operator Question] <Title>"
labels: ["node-operator", "discussion-metrics"]
body:
  - type: markdown
    attributes:
      value: |
        # Node Operator Questions
        
        Before proceeding, please consult the following resources.

  - type: checkboxes
    id: verify-check-docs
    attributes:
      label: Did you check the documentation?
      description: Please let us know how we can improve our [docs](https://docs.optimism.io/builders/node-operators/overview) in the additional information section.
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: verify-check-discussions
    attributes:
      label: Did you check for duplicate questions?
      description: Please check the existing [discussion](https://github.com/ethereum-optimism/developers/discussions) questions first. [How to search GitHub discussions](https://docs.github.com/en/search-github/searching-on-github/searching-discussions)
      options:
        - label: "Yes"
          required: true
        
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please describe, in detail, the issue you are having.
    validations:
      required: true

    - type: textarea
      id: protocol-description
      attributes:
        label: Protocol Description
        description: |
          Please provide:
            - `op-geth` version
            - `op-node` version
            - network name 
            - chainid
            - L1 chain
      validations:
        required: true

  - type: textarea
    id: node-logs
    attributes:
      label: Node Logs
      description: Please copy and paste relevant logs from the `op-node` and/or `op-geth`.

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please provide any additional information that may help us answer your question.

  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: How can we improve? Are there documentation or resources that don't exist and would serve you better?
