title: '[Node Operator Question] <Title>'
labels:
  - node-operator
  - discussion-metrics
body:
  - type: markdown
    attributes:
      value: |
        # Node Operator Questions

        Before proceeding, please consult the following resources.
  - type: checkboxes
    id: verify-latest-software
    attributes:
      label: Are you running the most up to date node software?
      description: >-
        We only support the latest software releases. See our
        [documentation](https://docs.optimism.io/builders/node-operators/releases)
        to check if you're up to date.
      options:
        - label: 'Yes'
          required: true
  - type: checkboxes
    id: verify-check-docs
    attributes:
      label: Did you check the documentation?
      description: >-
        If our [documentation](https://docs.optimism.io/) didn't answer your
        question, please let us know how we can improve them by giving us
        [feedback](https://github.com/ethereum-optimism/developers/discussions/categories/feedback).
      options:
        - label: 'Yes'
          required: true
  - type: checkboxes
    id: verify-check-discussions
    attributes:
      label: Did you check for duplicate questions?
      description: >-
        Please check the open and closed
        [discussions](https://github.com/ethereum-optimism/developers/discussions)
        questions first. [How to search GitHub
        discussions](https://docs.github.com/en/search-github/searching-on-github/searching-discussions)
      options:
        - label: 'Yes'
          required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: >
        Please describe, in detail, the issue you are experiencing, including
        any error messages or unusual behavior.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: >
        Provide a step-by-step explanation of how to reproduce the issue. Please
        be as detailed as possible.
    validations:
      required: true
  - type: checkboxes
    id: component-affected
    attributes:
      label: Which component is affected?
      options:
        - label: op-geth
        - label: op-node
        - label: Other
    validations:
      required: true
  - type: textarea
    id: expected-vs-actual-behavior
    attributes:
      label: Expected vs. Actual Behavior
      description: >
        Describe what you expected to happen and what actually occurred. 

        This helps us understand how the issue is deviating from normal
        behavior.
    validations:
      required: true
  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: |
        Please provide the details of your environment, including:
          - Operating System (e.g., Ubuntu 20.04, macOS Ventura)
          - Hardware specifications (e.g., CPU, memory, disk space)
          - Software versions 
          - Any other relevant setup information
    validations:
      required: true
  - type: textarea
    id: protocol-description
    attributes:
      label: Protocol Information
      description: |
        Please provide:
          - `op-geth` version
          - `op-node` version
          - network name 
          - chain ID
          - L1 chain (e.g., Ethereum, Optimism, etc.)
    validations:
      required: true
  - type: textarea
    id: node-logs
    attributes:
      label: Node Logs
      description: >
        Copy and paste the relevant log entries related to the issue (e.g., from
        `op-node` or `op-geth`). This will help us diagnose the problem.
  - type: textarea
    id: troubleshooting-attempts
    attributes:
      label: Troubleshooting Attempts
      description: |
        Please describe any steps you've taken to resolve the issue on your own.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: >
        Provide any other relevant details, such as configuration settings,
        recent changes, or attempts to resolve the issue.
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: >
        How can we improve? Are there missing documentation or resources that
        would better support you?
